# This workflow release uni-flatten to npm registry

name: release

on:
  push:
    branches: [main, next, alpha]

permissions:
  contents: read # for checkout

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Github Action account
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint:dontfix

      - name: Check Formatting
        run: pnpm run format:dontfix

      - name: Coverage
        run: pnpm run test:cov

      - name: Build before release
        run: pnpm run build

      - name: Release
        run: pnpm run release
